# Generated by Django 5.2.5 on 2025-08-21 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(editable=False)),
                ('conge_restant_annee_n_2', models.IntegerField(default=0, editable=False)),
                ('conge_restant_annee_n_1', models.IntegerField(default=0, editable=False)),
                ('conge_restant_annee_courante', models.IntegerField(default=0, editable=False)),
                ('conge_initial', models.IntegerField(default=0)),
                ('conge_total', models.IntegerField(default=0, editable=False)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='personnel.personnel')),
            ],
            options={
                'ordering': ['-annee'],
                'unique_together': {('personnel', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(editable=False)),
                ('conge_demande', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('debut_conge', models.DateField(blank=True, null=True)),
                ('periode', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('motif', models.TextField(blank=True, null=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, editable=False, null=True)),
                ('annule', models.BooleanField(blank=True, null=True)),
                ('date_annulation', models.DateTimeField(blank=True, editable=False, null=True)),
                ('conge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='conges.conge')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_conges', to='personnel.personnel')),
            ],
            options={
                'ordering': ['-date_soumission'],
            },
        ),
    ]
