# Generated by Django 5.2.5 on 2025-08-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeconge',
            name='annee',
        ),
    ]
