# Generated by Django 5.2.5 on 2025-08-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0002_remove_demandeconge_annee'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeconge',
            name='annee',
            field=models.IntegerField(default=2025, editable=False),
        ),
    ]
