# Generated by Django 5.2.5 on 2025-08-29 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0003_demandeconge_annee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegleConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conge_initial_tech', models.IntegerField(default=72)),
                ('conge_initial_autres', models.IntegerField(default=45)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regles_conges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
