# Generated by Django 5.2.5 on 2025-09-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0004_regleconge'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='conge_compasatoire',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='conge',
            name='conge_exceptionnel',
            field=models.IntegerField(default=6),
        ),
    ]
