# Generated by Django 5.2.5 on 2025-09-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0005_conge_conge_compasatoire_conge_conge_exceptionnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='conge_compasatoire',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
