# Generated by Django 5.2.5 on 2025-10-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0006_alter_conge_conge_compasatoire'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='conge_mensuel_restant',
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
