# Generated by Django 5.2.5 on 2025-10-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0007_conge_conge_mensuel_restant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='conge_restant_annee_courante',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='conge',
            name='conge_restant_annee_n_1',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='conge',
            name='conge_restant_annee_n_2',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='conge',
            name='conge_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
    ]
