# Generated by Django 5.2.5 on 2025-11-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conges", "0008_alter_conge_conge_restant_annee_courante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conge",
            name="quota_mensuel",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=5
            ),
        ),
    ]
