# Generated by Django 5.2.5 on 2025-11-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conges", "0009_conge_quota_mensuel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conge",
            name="quota_mensuel",
        ),
    ]
