# Generated by Django 5.2.5 on 2025-09-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nombre_enfants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='partenaire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='situation_familiale',
            field=models.CharField(blank=True, choices=[('celibat', 'Célibataire'), ('veuf', 'Veuf (ve)'), ('divorce', 'Divorcé (e)'), ('marie', 'Marié (e)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telephone_mobile',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
