# Generated by Django 5.2.5 on 2025-09-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_nombre_enfants_customuser_partenaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='certificats_academiques',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nationalite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
