# Generated by Django 5.2.5 on 2025-10-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='niveau_etudes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
