# Generated by Django 5.2.5 on 2025-11-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_customuser_double_auth_trusteddevice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trusteddevice",
            name="name",
        ),
        migrations.AddField(
            model_name="passwordresetcode",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="trusteddevice",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
