# Generated by Django 5.2.5 on 2025-08-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenoms', models.CharField(max_length=150)),
                ('grade', models.CharField(choices=[('ouvrier', 'Ouvrier'), ('administrateur', 'Administrateur'), ('technicien', 'Technicien')], max_length=50)),
                ('specialite', models.CharField(max_length=150)),
                ('ecole_origine', models.CharField(max_length=150)),
                ('cin', models.CharField(max_length=20, unique=True)),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('pv_affectation', models.FileField(blank=True, null=True, upload_to='pv/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('decret_officiel', models.FileField(blank=True, null=True, upload_to='decrets/')),
                ('fiche_fonction', models.FileField(blank=True, null=True, upload_to='fiche_fonction/')),
                ('date_affectation', models.DateField()),
                ('date_passage_grade', models.DateField()),
                ('fiche_module_fr', models.FileField(blank=True, null=True, upload_to='fiche_module/fr/')),
                ('fiche_module_en', models.FileField(blank=True, null=True, upload_to='fiche_module/en/')),
            ],
        ),
    ]
