# Generated by Django 5.2.5 on 2025-09-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_personnel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='code_postal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='pays',
            field=models.CharField(default='Tunisie', max_length=255),
        ),
        migrations.AddField(
            model_name='personnel',
            name='ville',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='grade',
            field=models.CharField(max_length=255),
        ),
    ]
