# Generated by Django 5.2.5 on 2025-09-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_personnel_adresse_personnel_code_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='pays',
            field=models.CharField(blank=True, default='Tunisie', max_length=255, null=True),
        ),
    ]
