# Generated by Django 5.2.5 on 2025-09-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_alter_personnel_pays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='ville',
        ),
    ]
