# Generated by Django 5.2.5 on 2025-10-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_personnel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='rang',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
