# Generated by Django 5.2.5 on 2025-11-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0007_personnel_rang"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnel",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
